### PR TITLE
PageController: fix: isEnabledForUser call: use currently logged user

### PR DESCRIPTION
**Pull request by btakita**
Fixes https://github.com/nextcloud/integration_miro/issues/5

```php
$talkEnabled = $this->appManager->isEnabledForUser('spreed');
```

### CODE REVIEW

**Comment by provokateurin** [comment]
Thanks for the quick fix! I think we still need to pass the user to the method. I assume this code was broken before because using the string should have never worked

**Comment by provokateurin** [comment]
A patch like this should do the job:
[patch.txt](https://github.com/nextcloud/integration_miro/files/11998743/patch.txt)

**Review by provokateurin — APPROVED** [review]

**Comment by btakita** [comment]
@provokateurin Thank you for your help on this PR!

**Review by julien-nc — CHANGES_REQUESTED** [review]
Hey, thanks a lot for the PR.
There is no need to get the user to pass it to `isEnabledForUser` as it checks for the currently logged in user by default. We can just remove the 2nd param.

**Comment by provokateurin** [comment]
Oh I see, I didn't look at it properly. @julien-nc let's just go with your PR to quickly fix it.

**Comment by julien-nc** [comment]
Thanks @btakita anyway!

**Pull request closed without merging**
